DROP TABLE IF EXISTS Candidate;
CREATE TABLE Candidate(
            `CandidateID` INT NOT NULL AUTO_INCREMENT,
            `jobInterest` VARCHAR(64),
            `jobType` VARCHAR(64),
            `jobCV` VARCHAR(64),
            `transportation` VARCHAR(64),
            `LicenseNumber` VARCHAR(64),
            `classLicense` VARCHAR(64),
            `endorsement` VARCHAR(64) ,
            `citizenship` VARCHAR(64) ,
            `nationality` VARCHAR(64) ,
            `passportCountry` VARCHAR(64) ,
            `passportNumber` VARCHAR(64) ,
            `compensationInjury` VARCHAR(64) ,
            `compensationDateFrom` VARCHAR(64) ,
            `compensationDateTo` VARCHAR(64) ,
            `asthma` VARCHAR(8),
            `blackOut` VARCHAR(8),
            `diabetes` VARCHAR(8),
            `bronchitis` VARCHAR(8),
            `backInjury` VARCHAR(8),
            `deafness` VARCHAR(8),
            `dermatitis` VARCHAR(8),
            `skinInfection` VARCHAR(8),
            `allergies` VARCHAR(8),
            `hernia` VARCHAR(8),
            `highBloodPressure` VARCHAR(8),
            `heartProblems` VARCHAR(8),
            `usingDrugs` VARCHAR(8),
            `usingContactLenses` VARCHAR(8),
            `RSI` VARCHAR(8),
            `dependants` VARCHAR(8),
            `smoke` VARCHAR(8),
            `conviction` VARCHAR(8),
            `convictionDetails` VARCHAR(64),
            `UserID` int,
            `JobID` int,
            PRIMARY KEY(CandidateID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;