DROP TABLE IF EXISTS `Citizenship`;
CREATE TABLE `Citizenship` (
    ID INT NOT NULL AUTO_INCREMENT,
    Citizenship varchar(64),
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Afghanistan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Åland Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Albania");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Algeria");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("American Samoa");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Andorra");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Angola");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Anguilla");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Antarctica");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Antigua and Barbuda");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Argentina");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Armenia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Aruba");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Australia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Austria");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Azerbaijan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Bahamas");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Bahrain");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Bangladesh");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Barbados");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Belarus");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Belgium");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Belize");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Benin");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Bermuda");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Bhutan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Bolivia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Bosnia and Herzegovina");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Botswana");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Bouvet Island");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Brazil");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("British Indian Ocean Territory");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Brunei Darussalam");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Bulgaria");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Burkina Faso");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Burundi");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Cambodia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Cameroon");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Canada");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Cape Verde");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Cayman Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Central African Republic");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Chad");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Chile");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("China");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Christmas Island");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Cocos (Keeling) Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Colombia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Comoros");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Congo");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Congo, The Democratic Republic of The");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Cook Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Costa Rica");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Cote D'ivoire");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Croatia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Cuba");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Cyprus");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Czech Republic");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Denmark");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Djibouti");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Dominica");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Dominican Republic");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Ecuador");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Egypt");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("El Salvador");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Equatorial Guinea");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Eritrea");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Estonia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Ethiopia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Falkland Islands (Malvinas)");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Faroe Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Fiji");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Finland");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("France");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("French Guiana");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("French Polynesia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("French Southern Territories");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Gabon");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Gambia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Georgia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Germany");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Ghana");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Gibraltar");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Greece");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Greenland");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Grenada");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Guadeloupe");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Guam");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Guatemala");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Guernsey");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Guinea");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Guinea-bissau");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Guyana");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Haiti");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Heard Island and Mcdonald Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Holy See (Vatican City State)");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Honduras");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Hong Kong");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Hungary");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Iceland");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("India");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Indonesia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Iran, Islamic Republic of");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Iraq");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Ireland");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Isle of Man");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Israel");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Italy");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Jamaica");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Japan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Jersey");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Jordan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Kazakhstan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Kenya");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Kiribati");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Korea, Democratic People's Republic of");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Korea, Republic of");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Kuwait");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Kyrgyzstan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Lao People's Democratic Republic");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Latvia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Lebanon");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Lesotho");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Liberia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Libyan Arab Jamahiriya");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Liechtenstein");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Lithuania");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Luxembourg");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Macao");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Macedonia, The Former Yugoslav Republic of");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Madagascar");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Malawi");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Malaysia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Maldives");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Mali");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Malta");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Marshall Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Martinique");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Mauritania");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Mauritius");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Mayotte");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Mexico");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Micronesia, Federated States of");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Moldova, Republic of");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Monaco");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Mongolia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Montenegro");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Montserrat");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Morocco");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Mozambique");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Myanmar");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Namibia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Nauru");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Nepal");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Netherlands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Netherlands Antilles");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("New Caledonia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("New Zealand");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Nicaragua");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Niger");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Nigeria");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Niue");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Norfolk Island");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Northern Mariana Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Norway");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Oman");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Pakistan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Palau");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Palestinian Territory, Occupied");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Panama");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Papua New Guinea");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Paraguay");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Peru");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Philippines");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Pitcairn");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Poland");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Portugal");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Puerto Rico");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Qatar");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Reunion");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Romania");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Russian Federation");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Rwanda");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Saint Helena");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Saint Kitts and Nevis");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Saint Lucia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Saint Pierre and Miquelon");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Saint Vincent and The Grenadines");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Samoa");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("San Marino");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Sao Tome and Principe");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Saudi Arabia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Senegal");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Serbia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Seychelles");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Sierra Leone");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Singapore");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Slovakia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Slovenia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Solomon Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Somalia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("South Africa");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("South Georgia and The South Sandwich Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Spain");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Sri Lanka");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Sudan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Suriname");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Svalbard and Jan Mayen");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Swaziland");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Sweden");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Switzerland");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Syrian Arab Republic");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Taiwan, Province of China");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Tajikistan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Tanzania, United Republic of");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Thailand");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Timor-leste");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Togo");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Tokelau");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Tonga");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Trinidad and Tobago");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Tunisia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Turkey");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Turkmenistan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Turks and Caicos Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Tuvalu");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Uganda");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Ukraine");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("United Arab Emirates");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("United Kingdom");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("United States");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("United States Minor Outlying Islands");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Uruguay");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Uzbekistan");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Vanuatu");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Venezuela");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Viet Nam");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Virgin Islands, British");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Virgin Islands, U.S.");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Wallis and Futuna");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Western Sahara");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Yemen");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Zambia");
INSERT INTO `Citizenship` (`Citizenship`) VALUES ("Zimbabwe");